apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: service_nginx
        imagePullPolicy: Never
        name: nginx
        ports:
          - containerPort: 80
            name: nginx-http
          - containerPort: 443
            name: nginx-https