apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: dfault
      protocol: layer2
      addresses:
      - MINIKUBE_IP40-192.168.49.250