apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - port: 20
      name: ftps-data
    - port: 21
      name: ftps
    - port: 21000
      name: ftps-passive-0
    - port: 21001
      name: ftps-passive-1